name: Exp
description: Exp plugin
author: MagicDroidX (c) 2011-2015
api: 1.12.0
version: 2.0.5
main: MagicDroidX\Exp
commands:
  glory:
    description: Purchase Items with glory
    usage: /glory <player> <amount>
  setgrade:
    description: Set the player level
    usage: /setgrade <player> <lvl>
  giveglory:
    desciption: Give players glory 
    usage: /giveglory <player> <amount>
  health:
    description: set a players max health
    usage: /health <player> <amount>
  money:
    description: Daily reward money
    usage: /money
  skills:
    description: Learn Skills
    usage: /skills <ID> <amount>
  setskills:
    description: Set skills for player
    usage: /setskills <player> <amount>
  qdskills:
    description: Sign up for skills [SVIP]
    usage: /qdskills
