name: Exp
description: Exp plugin
author: MagicDroidX (c) 2011-2015
api: 1.0.0
version: 1.0.0e1
main: MagicDroidX\Exp
commands:
  glory:
    description: get item by using glory
    usage: /glory <ID> <number>
  setgrade:
    description: Set grade for a player
    usage: /setgrade <player> <level>
  giveglory:
    desciption: give glory to a player
    usage: /giveglory <player> <number>
  health:
    description: Set Max health for a player
    usage: /health <player> <number>
  money:
    description: Sign Daily
    usage: /money
  skills:
    description: study skills
    usage: /skills <ID> <number>
  setskills:
    description: set skills for a player
    usage: /setskills <player> <number>
  qdskills:
    description: Sign up for skills [SVIP]
    usage: /qdskills
